/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as governanceTokenWrapperSol from "./GovernanceTokenWrapper.sol";
export type { governanceTokenWrapperSol };
